title: Xiaozhe (Josh) Zhang # your name (or website title) here
logo: "/images/IMG_5725.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Edit these links below   
  <a href="https://www.linkedin.com/in/zxzjosh/">LinkedIn</a> 
  <br>
  <a href="/pdf/Xiaozhe Zhang_Lehigh_2023.pdf" class="btn btn--info">Resume</a>    
  <br>
  <a href="https://github.com/XiaozheZhangLehigh">GitHub</a>  
  
theme: jekyll-theme-minimal
